POP procedural oriented programming
OOP object oriented programming

POP:
Prog divided into functions
intuitive incremental top down design
complex code
OOP:
program dicided into objects
object focused bottom up design
complex design (abstraction)
OOP increases readablilty of code

POP can be decomposed into 
1 set of class
2 set of functions that operate on data
3 the main program

issues
consider box of type rectangel with attributes w, h
in order to compute the area we may want to create a computer_area function using box as argument
if in the same code we now want to xconsider an object hole of type circle with attribute r for radius and we do want to compue the area
we would need to rename the function above to rectange specific and circle specific
becomes complex to manage if we have tens of shapes

In [1]:
#POP
class Rectangle:
    def __init__(self,width=0,height=0):
        self.w=width
        self.h=height

def compute_area(rect):
    return rect.w*rect.h

box1=Rectangle(200,100)
a=compute_area(box1)
print("area =", a)

area = 20000


In [6]:
#OOP
#POP
class Rectangle:
    def __init__(self,width=0,height=0):
        self.w=width
        self.h=height
        
    def compute_area(self):
        return self.w*self.h

box1=Rectangle(200,100)
a=box1.compute_area(box1)
print("area =", a)

TypeError: Rectangle.compute_area() takes 1 positional argument but 2 were given

In [14]:
class Rectangle:
    def __init__(self,width=0,height=0):
        self.w=width
        self.h=height
    def compute_area(self):
        return self.w*self.h
    def info(self):
        print(f"w={self.w}; h={self.h}")
    def scale(self, factor):
        self.w=self.w*factor
        self.h=self.h*factor
    def get_scaled_rectangle(self,factor):
        return Rectangle(self.w*factor,self.h*factor)

box1=Rectangle(100,100)
box1.info()
a=box1.compute_area()
print("area=", a)
box1.scale(2)
a=box1.compute_area()
box1.info()
print("new area=", a)

for i in range(10):
    box=box1.get_scaled_rectangle(2)
    a=box.compute_area()
    print('area=',a)


w=100; h=100
area= 10000
w=200; h=200
new area= 40000
area= 160000
area= 160000
area= 160000
area= 160000
area= 160000
area= 160000
area= 160000
area= 160000
area= 160000
area= 160000


In [6]:
import numpy as np
f = np.arange(10)
print(f)
f = np.linspace(1,10,6)
print(f)
f = np.zeros(4)
A = np.zeros((2,2))
print(A)
print(f)

[0 1 2 3 4 5 6 7 8 9]
[ 1.   2.8  4.6  6.4  8.2 10. ]
[[0. 0.]
 [0. 0.]]
[0. 0. 0. 0.]
